ADD: player model and view, EDIT: controller
hannahtwiggsmith/SoftSysHedonisticHibiscus pull request #6
Opened 2017-04-05 14:11 UTC by hannahtwiggsmith

Player can now be moved by WASD and arrow keys. This is very preliminary and a little hacky, I'm expecting there to be some architectural changes.

2017-04-05 14:24 UTC, segerphilip reviewed
Looks good 🚢 🇮🇹

2017-04-05 14:24 UTC, segerphilip commented on src/La Trop/controller/controller.cpp
> +            _view->render(); // Might want to change render function so it only updates screen/doesnt re-render everything
agreed, not sure how that should be changed yet though

2017-04-05 14:24 UTC, segerphilip approved these changes

2017-04-06 00:04 UTC, sammyers requested changes
Looks good overall.

2017-04-06 00:04 UTC, sammyers commented on src/La Trop/model/player.hpp
> +#include "../view/player.hpp"
why

2017-04-06 00:04 UTC, sammyers commented on src/La Trop/controller/controller.cpp
> +            _view->render(); // Might want to change render function so it only updates screen/doesnt re-render everything
These changes should get rendered in the main loop.

2017-04-06 00:10 UTC, segerphilip commented
Also required because of my changes, `brew install freeglut`

2017-04-06 00:38 UTC, sammyers approved these changes

2017-04-06 00:39 UTC, merged